#Server configuration .....
server:
  port: 9090

#Spring configuration .....
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true